# Site
name: "Blog"
title: "Hello World"
description: "A website hosted with github pages"
meta_description: "A website hosted with github pages"
logo: 'assets/images/logo.png'
favicon: '/favicon.ico'
baseurl: ""
google_analytics: 'UA-33110211-1'
# disqus: 'demowebsite'
mailchimp-list: 'https://helloworld.us14.list-manage.com/subscribe?u=7d32137885f6a0cea7bb073d8&id=fcdca7faa6'
# Authors
authors:
  bukhbayar:
    name: Bukhbayar Purevsuren
    display_name: Bukhbayar
    gravatar: bc1aff1eabac45bb90eff3419993e95f
    email: bokhbayar@gmail.com
    web: https://helloworld.mn
    twitter: https://twitter.com/bokhoo
    description: ""
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge